version: "2"
checks:
  argument-count:
    enabled: false

  method-complexity:
    enabled: true
    config:
      threshold: 10

  method-lines:
    enabled: true
    config:
      threshold: 35

  file-lines:
    config:
      threshold: 460

  return-statements:
    config:
      threshold: 6
