language: python
sudo: false
cache: pip

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy

env:
  - TOXENV=py,flask,django,codecov

install:
  - pip install -U setuptools
  - pip install tox

script: tox

notifications:
  email: false
