language: python
sudo: false
cache: pip

matrix:
  include:
  - python: 2.7
    env: TOXENV=py,flask,py27-django,codecov
  - python: 3.5
    env: TOXENV=py,flask,py35-django,codecov
  - python: 3.6
    env: TOXENV=py,flask,py36-django,codecov

install:
  - pip install -U setuptools
  - pip install tox

script: tox

notifications:
  email: false
